CrowdFunding/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='CrowdFunding'
urlpatterns = [
    path('', views.show_hello_world, name='show_hello_world'),
    path('admin/', admin.site.urls),
    path('registrasi', include('Donatur.urls'))
]

Donasi/urls.py
from django.urls import path
from . import views

app_name='Donasi'
urlpatterns = [
    path('', views.view_form_donasi, name="view_form_donasi"),
    path('buat_donasi', views.buat_donasi, name="buat_donasi"),
    path('donasi_berhasil', views.donasi_berhasil, name="donasi_berhasil"),
]

Donatur/urls.py
from django.urls import path
from .views import registration, submit

app_name='Donatur'
urlpatterns = [
    path('', registration, name='registrasi'),
    path('done/', submit, name='submit')
]

TugasPemrograman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from program.views import program

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CrowdFunding.urls')),
    path('about/', include('about.urls')),
    path('program/', include('program.urls')),
    path('registrasi/', include('Donatur.urls')),
    path('login/', include('login.urls')),
    path('donasi/', include('Donasi.urls')),
    path('news/', include('news.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('list_donasi/', include('donation_history.urls')),
]

news/urls.py
from django.urls import path
from .views import *
#di url project udah manggil news. jadi di url app gausah manggil lagi
app_name='news'
urlpatterns = [
    path('', indexNews, name='indexNews'),
    path('berita1/', berita1, name='berita1'),
    path('berita2/', berita2, name='berita2'),
    path('berita3/', berita3, name='berita3'),
]

program/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name='program'
urlpatterns = [
    path('',program,name='program'),
]

Donatur/models.py
from django.db import models

class Donatur(models.Model):
    namadonatur = models.CharField(max_length=40)
    tanggallahir = models.DateField()
    email = models.EmailField()
    password = models.CharField(max_length=20)

Donatur/forms.py
from django import forms
from .models import Donatur

class Donatur_Form(forms.Form):
    attrsname = {
        'class' : 'form-control',
        'placeholder' : 'Masukan namamu'
    }

    attrsdate = {
        'class' : 'form-control',
        'placeholder' : 'Masukan tanggal lahirmu',
        'type' : 'date'
    }

    attrsemail = {
        'class' : 'form-control',
        'placeholder' : 'Masukan emailmu'
    }

    attrspassword = {
        'class' : 'form-control',
        'placeholder' : 'Masukan password',
        'type' : 'password'
    }



    name = forms.CharField(label='Nama', required=True, max_length=40, widget=forms.TextInput(attrs=attrsname))
    date = forms.DateTimeField(label='Tanggal Lahir', required=True, widget=forms.DateInput(attrs=attrsdate))
    email = forms.EmailField(label='Email', required=True, max_length=30, widget=forms.TextInput(attrs=attrsemail))
    new_password = forms.CharField(label='Password', required=True, max_length=30, widget=forms.TextInput(attrs=attrspassword))
    #confirm_password = forms.CharField(label='Konfirmasi Password', required=True, max_length=30, widget=forms.TextInput(attrs=attrspassword))

    #def clean_password(self):
    #    new_password = self.cleaned_data.ge("new_password")
    #    confirm_password = self.cleaned_data.get("confirm_password")
    #    if (new_password == confirm_password):
    #       return confirm_password
    #    else:
    #        raise forms.ValidationError("Password tidak sama")

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            match = Donatur.objects.get(email=email)
        except Donatur.DoesNotExist:
            return email
        raise forms.ValidationError('Email sudah terdaftar')

Donatur/views.py
from django.shortcuts import render
from .models import Donatur
from .forms import Donatur_Form
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm

def submit(request):
    form = Donatur_Form(request.POST)
    if request.method == 'POST' and form.is_valid():
        response = {}
        response['name'] = request.POST['name']
        response['date'] = request.POST['date']
        response['email'] = request.POST['email']
        response['password'] = request.POST['new_password']
        akun = Donatur(namadonatur=response['name'], tanggallahir = response['date'],
                          email=response['email'], password=response['password'])
        akun.save()
        return render(request, 'doneregis.html', response)
    else:
        return render(request, 'registration.html', {'regisform': form})

def registration(request):
    return render(request, "registration.html", {'regisform' : Donatur_Form})

Donatur/templates/doneregis.html
{% extends "landingTemplate.html" %}

{% block title %} Sinarperak Donasi {% endblock %}

{% block content %}
<div class="container quote-box">
	<p class=quote>
		Terima kasih telah mendaftarkan diri menjadi donatur.</b><br>
	</p>
	<br>
	<a  href="{% url 'program:program' %}"></a><button type="button" class="btn button-daftar landing-button">AYO DONASI</button></a>
</div>
{% endblock %}

Donatur/templates/navfootTemplate.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
		{% endblock %}
	</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	<!-- Stylesheet -->
	<link rel="stylesheet" href="{% static 'css/navbarStyle.css' %}">
	<link rel="stylesheet" href="{% static 'css/registrationStyle.css' %}">

</head>
<body>
	<!-- Image and text -->
  		<nav class="navbar navbar-expand-lg navbar-light bg-orange">
  			<a class="navbar-brand navbar-text  brand" href="{% url 'CrowdFunding:show_hello_world' %}">
		    	<img src="{% static 'Logo-sinarperak.png' %}" class="d-inline-block align-top logo" alt="">
		    	SINARPERAK
		  	</a>
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		   	 <span class="navbar-toggler-icon"></span>
		  	</button>
		  	<div style="float: left;width:100vw;"></div>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <div class="navbar-nav menu">
		      <a class="nav-item nav-link" href="{% url 'program:program' %}">Program</a>
		      <a class="nav-item nav-link" href="{% url 'news:indexNews' %}">Berita</a>
		      <a class="nav-item nav-link" href="{% url 'Donasi:view_form_donasi' %}">Donasi</a>
		      <a class="nav-item nav-link" href="{% url 'Donatur:registrasi' %}"><button type="button" class="btn btn-outline-secondary button">Masuk</button></a>
		      <a class="nav-item nav-link" href="{% url 'Donatur:registrasi' %}"><button type="button" class="btn button-daftar">Daftar</button></a>
		    </div>
		  </div>
		</nav>
		<img src="{% static '70711-senyum-keceriaan-anak-pengungsi-korban-gempa-lombok.jpg' %}" class="bg-img">
<div style="height: auto;">
{% block content %}
{% endblock %}
</div>
	<div class="jumbotron bg-orange footer">
  		<div class="container" style="padding:0rem; margin-left: 0px">
    		<h5 class="footer-tag">Copyright © 2018 Sinar Perak. All rights reserved. </h5>
    	</div>
    </div>
</body>
</html>

Donatur/templates/registration.html
{% include "navbarFooter.html" %}
{% load static %}

{% block title %} Registrasi Donatur {% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/navbarStyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/registrationStyle.css' %}">
{% endblock %}

{% block content %}
<br><br>

{% if messages %}
    {% for message in messages %}
        <h2 style="color: red; text-align: center;">{{ message }}</h2>
    {% endfor %}
{% endif %}

<br><br>
<div class="regis-box">
	<br>
    <h1 class="regis-title"><b>REGISTRASI</b></h1>
    <form id="form" method="POST" action="{% url 'Donatur:submit' %}">
        {% csrf_token %}
        <div class="regis-form">
        {{ regisform }}
    	</div>
        <br>
        <div class="submit">
        	<button type="submit" class="btn btn-outline-secondary button btn-lg regis-btn">Daftar</button></a>
        </div>
        <br>
    </form>
</div>
{% endblock %}