CrowdFunding/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='CrowdFunding'
urlpatterns = [
    path('', views.show_hello_world, name='show_hello_world'),
    path('admin/', admin.site.urls),
    path('registrasi', include('Donatur.urls'))
]

Donasi/urls.py
from django.urls import path
from . import views

app_name='Donasi'
urlpatterns = [
    path('', views.view_form_donasi, name="view_form_donasi"),
    path('buat_donasi', views.buat_donasi, name="buat_donasi"),
    path('donasi_berhasil', views.donasi_berhasil, name="donasi_berhasil"),
]

Donatur/urls.py
from django.urls import path
from .views import registration, submit

app_name='Donatur'
urlpatterns = [
    path('', registration, name='registrasi'),
    path('done/', submit, name='submit')
]

TugasPemrograman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from program.views import program

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CrowdFunding.urls')),
    path('about/', include('about.urls')),
    path('program/', include('program.urls')),
    path('registrasi/', include('Donatur.urls')),
    path('login/', include('login.urls')),
    path('donasi/', include('Donasi.urls')),
    path('news/', include('news.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('list_donasi/', include('donation_history.urls')),
]

about/urls.py
from django.urls import path
from .views import *


app_name='About'
urlpatterns = [
    path('', indexAbout, name='indexAbout'),
    path('testimoni/', indexTestimoni, name='indexTestimoni'),
]

news/urls.py
from django.urls import path
from .views import *
#di url project udah manggil news. jadi di url app gausah manggil lagi
app_name='news'
urlpatterns = [
    path('', indexNews, name='indexNews'),
    path('berita1/', berita1, name='berita1'),
    path('berita2/', berita2, name='berita2'),
    path('berita3/', berita3, name='berita3'),
]

program/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name='program'
urlpatterns = [
    path('',program,name='program'),
]

about/models.py
from django.db import models 


class About(models.Model): 
    name = models.CharField(max_length=10)
    testimony = models.TextField(max_length=400)

about/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse 
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from .models import About 
import urllib.request, json, requests

def indexAbout(request):
    all_about = About.objects.all()
    return render(request, 'about.html', {'about': all_about})

def indexTestimoni(request):
    if request.method == 'POST':
        name = request.POST['name']
        testimony = request.POST['testimony']
        About.objects.create(name=name, testimony=testimony)
        return JsonResponse({'saved': True, 'name': name, 'testimony': testimony})
    return JsonResponse({'saved': False})

       

about/templates/about.html
{% extends 'navbarFooter.html' %}
{% load static %}

{% block title %}About Us{% endblock %}
<head>

{% block style %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/Javascript" src="{% static 'abouttesti.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/baseStyle.css' %}" type="text/css">
{% endblock %}
</head>

{% block content %}
<br>
<div class="container">
    <div class="row">
                <div class="col-md-12 about-s2">   
                    <h2 align="center" class="card-title berita-text"><strong>Tentang Kami</strong></h2>
                    <h4 class="card-text berita-text"> SinarPerak adalah sebuah platform untuk menggalang dana bersama.  
                     Kami mengajak teman-teman untuk bisa berpartisipasi memberikan sedekah kepada korban yang membutuhkan bantuan.</h4>
    </div></div>
</div>
<br>
    {% if user.is_authenticated %}
    <h2 align="center" class="card-title berita-text"><strong>Berikan Testimoni Kamu Disini </strong></h2><br>
        {% csrf_token %}
        <div class="container">
        <div class="row">
        <div class="col-md-24">
            <div class="form-group">
                <input id="id_name" size="50" type="text" name="nama-anda"  class="form-control" placeholder="Masukan namamu.." required="">
            </div>
            <div class="form-group">
                <textarea id="id_testimony" name="isi-pesan" class="form-control" placeholder="Berikan testimoni kamu disini...." cols="150" rows="5" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required" aria-required="true" aria-invalid="false"></textarea>
            </div>
            <div>
                <input id="id_button" onclick="testimoni()" class="btn btn-warning"  type="Submit" value="Submit">
            </div>
        </div></div></div>
    {% endif %} 

    
    <h2 align="center" class="card-title berita-text"><strong>Kata Mereka </strong></h2>
    
    <div class="card-deck berita-card" id="hasilTesti">
            {% for i in about %}
            <div class="d-flex align-content-around flex-wrap">
             <div id="main" style="display: flex;flex-wrap: wrap;justify-content:center; width: 250px;margin: 10px;text-align: center;line-height: 75px;font-size: 30px;">
            <div class="card">
                <div class="card-body berita-bg" style = "background-color: #3C444D;">
                    <p class="card-title berita-text" style="color:white;">{{ i.testimony }}</p>
                    <p class="card-text berita-text" style="color:white; text-align: right;" >{{ i.name }}</p> 
                </div>
            </div></div>
            {% endfor %}
        </div>
{% endblock %}

about/templates/navbarFooter.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>
		{% block title %}
		{% endblock %}
	</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
	 crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
	 crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
	 crossorigin="anonymous"></script>

	<!-- Stylesheet -->
	<link rel="stylesheet" href="{% static 'css/navbarDonasiStyle.css' %}">
	<link rel="stylesheet" href="{% static 'css/navbarStyle.css' %}">
	{% block style %}
	{% endblock %}

</head>

<body>
	<!-- Image and text -->
	<nav class="navbar navbar-expand-lg navbar-light bg-orange">  			
		<a class="navbar-brand navbar-text brand" href="{% url 'CrowdFunding:show_hello_world' %}">
		   	<img src="{% static 'Logo-sinarperak.png' %}" class="d-inline-block align-top logo" alt="">
		    	SINARPERAK
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02"
		 aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div style="float: left;width:100vw;"></div>
		<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
			<div class="navbar-nav menu">
				<a class="nav-item nav-link" href="{% url 'program:program' %}">Program</a>
				<a class="nav-item nav-link" href="{% url 'news:indexNews' %}">Berita</a>
				<a class="nav-item nav-link" href="{% url 'Donasi:view_form_donasi' %}">Donasi</a>
				{% if user.is_authenticated %}
				<div class="text-right" style="font-family: 'Signika', sans-serif; padding-right: 50px;">
					<br>
					<h3>Welcome, {{ user.first_name }} {{ user.last_name }}!</h3>
				</div>
				{% else %}
				<a class="nav-item nav-link" href="{% url 'Donatur:registrasi' %}"><button type="button" class="btn btn-outline-secondary button">Masuk</button></a>
				<a class="nav-item nav-link" href="{% url 'Donatur:registrasi' %}"><button type="button" class="btn button-daftar">Daftar</button></a>
				{% endif %}
			</div>
		</div>
	</nav>
	<img src="{% static '70711-senyum-keceriaan-anak-pengungsi-korban-gempa-lombok.jpg' %}" class="bg-img">

	<div>
		{% block content %}
		{% endblock %}
	</div>

	<div class="jumbotron bg-orange footer">
		<div class="container" style="padding:0rem; margin-left: 0px">
			<h5 class="footer-tag">Copyright © 2018 Sinar Perak. All rights reserved.</h5>
		</div>
	</div>
</body>

</html>