Donasi/urls.py
from django.urls import path
from . import views

app_name='Donasi'
urlpatterns = [
    path('', views.view_form_donasi, name="view_form_donasi"),
    path('buat_donasi', views.buat_donasi, name="buat_donasi"),
    path('donasi_berhasil', views.donasi_berhasil, name="donasi_berhasil"),
]

Donatur/urls.py
from django.urls import path
from .views import registration, submit

app_name='Donatur'
urlpatterns = [
    path('', registration, name='registrasi'),
    path('done/', submit, name='submit')
]

TugasPemrograman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from program.views import program

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CrowdFunding.urls')),
    path('about/', include('about.urls')),
    path('program/', include('program.urls')),
    path('registrasi/', include('Donatur.urls')),
    path('login/', include('login.urls')),
    path('donasi/', include('Donasi.urls')),
    path('news/', include('news.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('list_donasi/', include('donation_history.urls')),
]

about/urls.py
from django.urls import path
from .views import *


app_name='About'
urlpatterns = [
    path('', indexAbout, name='indexAbout'),
    path('testimoni/', indexTestimoni, name='indexTestimoni'),
]

login/urls.py
from django.urls import path
from .views import loginnya, logoutPage

app_name="Login"
urlpatterns = [
    path('', loginnya, name='login'),
    path('byebye/', logoutPage, name="logout")
]

news/urls.py
from django.urls import path
from .views import *
#di url project udah manggil news. jadi di url app gausah manggil lagi
app_name='news'
urlpatterns = [
    path('', indexNews, name='indexNews'),
    path('berita1/', berita1, name='berita1'),
    path('berita2/', berita2, name='berita2'),
    path('berita3/', berita3, name='berita3'),
]

program/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name='program'
urlpatterns = [
    path('',program,name='program'),
]

Donasi/models.py
from django.db import models
from Donatur.models import Donatur
from program.models import Program

class Donasi(models.Model):
    donatur = models.CharField(max_length=100)
    program = models.ForeignKey(Program, on_delete=models.CASCADE, default=None)
    jumlah_donasi = models.IntegerField(default=0)

    def __str__(self):
        return "Donasi " + self.donatur + " kepada " + self.program.judul

Donasi/forms.py
from django import forms
from program.models import Program
from Donatur.models import Donatur

class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.judul

class FormDonasi(forms.Form):
    program_attrs = {
        'class' : 'form-control',
    }

    donatur_attrs = {
        'class' : 'form-control',
        'placeholder': 'Nama lengkap'
    }

    email_attrs = {
        'class' : 'form-control',
        'placeholder' : 'Email'
    }

    jumlah_attrs = {
        'class' : 'form-control',
        'placeholder' : '0'
    }

    nama_program = MyModelChoiceField(required=True, queryset=Program.objects.all(), empty_label='Pilih program', to_field_name='judul', widget=forms.Select(attrs=program_attrs))
    # nama_donatur = forms.CharField(required=True, widget=forms.TextInput(attrs=donatur_attrs))
    # email = forms.EmailField(required=True, widget=forms.EmailInput(attrs=email_attrs))
    jumlah_donasi = forms.DecimalField(required=True, widget=forms.NumberInput(attrs=jumlah_attrs))
    donasi_sebagai_anonim = forms.BooleanField(required=False, widget=forms.CheckboxInput())

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     if (Donatur.objects.filter(email=email).exists()):
    #         return email
    #     else:
    #         raise forms.ValidationError('Email tidak terdaftar')

Donasi/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import FormDonasi
from .models import Donasi
from program.models import Program
from Donatur.models import Donatur
from donation_history.models import DonationHistory
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse, HttpResponse
import json

def view_form_donasi(request):
    if request.user.is_authenticated:
        form = FormDonasi()
        return render(request, 'form_donasi.html', {'form': form})
    else:
        notif = "Harap registrasi terlebih dahulu agar dapat melakukan donasi"
        messages.warning(request, notif)
        return HttpResponseRedirect('/login/')

@login_required
def buat_donasi(request):
    form = FormDonasi(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        nama_program = request.POST['nama_program']
        nama_donatur = request.session['first_name'] + " " + request.session['last_name']
        email = request.session['email']
        jumlah_donasi = request.POST['jumlah_donasi']
        donasi_sebagai_anonim = request.POST.get("donasi_sebagai_anonim")

        if donasi_sebagai_anonim:
            nama_donatur = 'Anonim'

        program = Program.objects.get(judul=nama_program)
        program.jumlah += int(jumlah_donasi)
        program.save()

        new_donasi = Donasi(donatur=nama_donatur, program=program, jumlah_donasi=int(jumlah_donasi))
        new_donasi.save()

        list_donasi = DonationHistory(program = program, name=nama_donatur, email = email, jumlah_donasi = jumlah_donasi)
        list_donasi.save()

        data = model_to_dict(list_donasi)

        return HttpResponseRedirect('/donasi/donasi_berhasil')
    return render(request, 'form_donasi.html', {'form': form})

def donasi_berhasil(request):
    return render(request, 'donasi_berhasil.html', {})

def model_to_dict(obj):
    data =  serializers.serialize('json',[obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]['fields'])
    return data

Donasi/templates/donasi_berhasil.html
{% load static %}
{% include "navbarFooter.html" %}

{% block title %} Form Donasi {% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/navbarDonasiStyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/formStyle.css' %}">
{% endblock %}

{% block content %}
    <br><br>
    <div class="donasi-box">
    	<br>
        <h1 class="donasi-title"><b>TERIMA KASIH ATAS DONASINYA</b></h1>
        <h2 class="donasi-form" align=center>Uluran tanganmu sangat berarti bagi mereka</h2>
        <br>
        <div class="submit">
            <a href="{% url 'CrowdFunding:show_hello_world' %}"><button type="button" class="btn btn-outline-secondary button btn-lg donasi-btn">Kembali ke halaman utama</button></a>
        </div>
        <br>
    </div>
{% endblock %}

Donasi/templates/form_donasi.html
{% include "navbarFooterDonasi.html" %}
{% load static %}

{% block content %}
    <br><br>
    <div class="donasi-box">
    	<br>
        <h1 class="donasi-title"><b>FORMULIR DONASI</b></h1>
        <form id="form" method="POST" action="{% url 'Donasi:buat_donasi' %}">
            {% csrf_token %}
            <div class="donasi-form">
            {{ form }}
        	</div>
            <br>
            <div class="submit">
            	<button type="submit" class="btn btn-outline-secondary button btn-lg donasi-btn">Donasi</button></a>
            </div>
            <br>
        </form>
    </div>
    <br>
{% endblock %}

Donasi/templates/navbarFooterDonasi.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		Form Donasi
	</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	<!-- Stylesheet -->
	<link rel="stylesheet" href="{% static 'css/navbarDonasiStyle.css' %}">
	<link rel="stylesheet" href="{% static 'css/formStyle.css' %}">

</head>
<body>
	<!-- Image and text -->
  		<nav class="navbar navbar-expand-lg navbar-light bg-orange">
  			<a class="navbar-brand navbar-text brand" href="{% url 'CrowdFunding:show_hello_world' %}">
		    	<img src="{% static 'Logo-sinarperak.png' %}" class="d-inline-block align-top logo" alt="">
		    	SINARPERAK
		  	</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		  	<div style="float: left;width:100vw;"></div>
		  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
		    <div class="navbar-nav menu">
		    	<a class="nav-item nav-link" href="{% url 'About:indexAbout' %}">Tentang Kami</a>
		      <a class="nav-item nav-link" href="{% url 'program:program' %}">Program</a>
		      <a class="nav-item nav-link" href="{% url 'news:indexNews' %}">Berita</a>
		      <a class="nav-item nav-link" href="{% url 'Donasi:view_form_donasi' %}">Donasi</a>
		      {% if user.is_authenticated %}
		      	<a class="nav-item nav-link" href="{% url 'donation_history:donations' %}">List Donasi</a>
				<div class="text-right" style="font-family: 'Signika', sans-serif; padding-right: 50px;">
					<h3>Welcome, {{ user.first_name }} {{ user.last_name }}!</h3>
				</div>
				<a class="nav-item nav-link" href="{% url 'Login:logout' %}"><button type="button" class="btn button-logout">Log Out</button></a>
				{% else %}
				<a class="nav-item nav-link" href="{% url 'Login:login' %}"><button type="button" class="btn btn-outline-secondary button">Masuk</button></a>
				<a class="nav-item nav-link" href="{% url 'Donatur:registrasi' %}"><button type="button" class="btn button-daftar">Daftar</button></a>
				{% endif %}
		    </div>
		  </div>
		</nav>
		<img src="{% static '70711-senyum-keceriaan-anak-pengungsi-korban-gempa-lombok.jpg' %}" class="bg-img">

	<div>
		{% block content %}
		{% endblock %}
	</div>

	<div class="jumbotron bg-orange footer">
  		<div class="container" style="padding:0rem; margin-left: 0px">
    		<h5 class="footer-tag">Copyright © 2018 Sinar Perak. All rights reserved.</h5>
    	</div>
    </div>
</body>
</html>